language: cpp
matrix:
  include:

# osx
    - os: osx
      osx_image: xcode13.4
      env: XCODE="true" CHECK="true"

before_install:
  - echo $CC
  - echo $LANG
  - echo $LC_ALL

before_script:
  # XXX osx on travis doesn't work w/ set -e, so turn it off :(
  - set +e
  - mkdir -p build || echo "Failed to mkdir build"
  - cd build || echo "Failed to cd build"
  - cmake -B_builds -GXcode     -DCMAKE_SYSTEM_NAME=iOS      -DCMAKE_OSX_DEPLOYMENT_TARGET=13.0     -DCMAKE_XCODE_ATTRIBUTE_ONLY_ACTIVE_ARCH=NO     -DCMAKE_IOS_INSTALL_COMBINED=YES .. || { echo "Failed to run cmake" ; exit 1 ; }

script:
  - cmake --build _builds --config Release --target json-c-static -- -sdk iphonesimulator
