language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - cppcheck
      - valgrind

os:
  - linux
  - osx

before_install:
  - echo $LANG
  - echo $LC_ALL
  - set -e

install:
  - sh autogen.sh

before_script:
  - ./configure

script:
  - make

after_success:
  - make check ; result=$?
  - if [ $result != 0 ]; then
      cat tests/*.log;
    fi
  - if type cppcheck &> /dev/null ; then cppcheck --error-exitcode=1 --quiet *.h *.c tests/ ; fi
  - exit $result
