version: '{branch}.{build}'

image:
  # VS2015 also used for earlier VS builds
  # aka os: Windows Server 2012 R2
  - Visual Studio 2015
  # aka os: Windows Server 2016
  - Visual Studio 2017
  # aka os: Windows Server 2019
  - Visual Studio 2019

platform: x64

for:
-
  matrix:
    only:
      - image: Visual Studio 2015

  environment:
    matrix:
      - b_toolset: Windows7.1SDK
        b_config: Debug

      - b_toolset: v120
        b_config: Debug

      - b_toolset: v140
        b_config: Debug

  build_script:
    - cmake -T %b_toolset% -DCMAKE_BUILD_TYPE=%b_config% -DCMAKE_INSTALL_PREFIX=t_install .
    - cmake --build . --target install

environment:
  matrix:
    - b_config: Debug

    - b_config: Release

build_script:
- cmake -DCMAKE_BUILD_TYPE=%b_config% -DCMAKE_INSTALL_PREFIX=t_install .
- cmake --build . --target install

after_build:
- cd t_install
- 7z a ../json-c.win32.%b_toolset%.%b_config%.zip *

artifacts:
- path: json-c.win32.%b_toolset%.%b_config%.zip
  name: json-c.win32.%b_toolset%.%b_config%.zip
